# [Exercise]{.exercise}

**Please hand in the R-Script and the plot 1.6 as pdf. Please add your name or name of group to the file/script names.**
  
  For example: MyWBPdf_course1\_<yourlastname><yourfirstname>.pdf and Rscript_course1<yourlastname>\_<yourfirstname>.Rmd/R

1.  Please load and inspect the following data set on wild boar observations in Berlin: `data_wb_melden_en.csv`. To load the data try both R functions, `read.csv()` and `read.table()`. You will find the data to download in the 'data' folder of the repository here:
  
  data → data_berlin → animal_data

The path to the file should look like: here("data", "data_berlin", "animal_data")

new_wd <- paste0(root_wd, "/", "data/data_berlin/animal_data")
setwd(new_wd)

wb <- read.csv("data_wb_melden_en.csv")

wb_t <- read.table("data_wb_melden_en.csv")

2.  Use the functions `head()`, `names()`, `levels()`, `str()`, `table()` (hint: choose a column), `hist()` (hint: choose a column), `summary()` and `plot()` to inspect the data.<br><br>

head(wb)
names(wb)
str(wb)
table(wb$year)
table(wb$group_size)
table(wb$n_piglets)
hist(wb$n_piglets)
hist(wb$group_size)
hist(wb$year)
summary(wb)
plot(wb$gps_x,wb$gps_y)
plot(wb$year,wb$group_size)
plot(wb$year,wb$n_piglets)
plot(wb$group_size,wb$n_piglets)

3.  Plot the number of piglets (`n_piglets`) per year.<br><br>

par(mfrow = c(1,1))

barplot(tapply(wb$n_piglets, INDEX=wb$year, FUN=sum, na.rm=TRUE), xlab="Year", ylab="No.of piglets")

boxplot(n_piglets~year, data=wb)

ggplot(wb, aes(year, n_piglets)) + geom_count(na.rm=TRUE) + ylab("No. of piglets") + scale_size_continuous(breaks = c(1,2,3,4,10,13))

4.  Now visualize only observations with more than four piglets and plot them over time (column `year`).<br><br>

pig_sub <- subset(wb, wb$n_piglets>=4)

barplot(tapply(pig_sub$n_piglets, INDEX=pig_sub$year, FUN=sum, na.rm=TRUE), xlab="Year", ylab="No.of piglets")

boxplot(n_piglets~year, data=pig_sub)

no_pig_by_yr<-by(pig_sub$n_piglets, pig_sub$year, table)

ggplot(pig_sub, aes(year, n_piglets)) + geom_count(aes(color=..n..),na.rm=TRUE) + ylab("No. of piglets")
  
5.  Create a column for the ratio of piglets vs the group size.<br>Afterwards visualize the number of piglets vs the year as a scatter plot and use a threshold of greater than 0.5 to colour the points.<br><br>

ratio<-wb$n_piglets/wb$group_size

wb<-cbind(wb,ratio)

ggplot(wb, aes(year, n_piglets)) + geom_count(aes(color= ifelse(ratio<0.5, 'NA', ifelse(ratio>2, 'lightblue', ifelse(ratio>=1,'blue','darkblue')))),na.rm=TRUE) + ylab("No. of piglets")+ scale_size_continuous(breaks = c(1,2,3,4,10,13)) + scale_color_manual(labels = c("> 2", ">= 1","> 0.5", "NA < 0.5"),values=c('lightblue','blue','darkblue', 'NA'))+ labs(color = "Ratio - Piglets per group")

6.  Create a bar plot for the weather column and give each bar a color.<br>Save this bar plot with a header and column names as a pdf.<br><br> <br>

myfilename <- paste0(output_wd,"/Course_1_weather_barplot_Kohrs_Susanne.pdf")

pdf(file = myfilename, width = 10, height = 10)

weather_barplot <- barplot(table(wb$weather),col=c('grey','blue','lightblue','darkblue','yellow'), ylab="Frequency", xlab= "Weather", main= "Weather frequency")

dev.off()

